AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  memiarka

  Sample SAM Template for memiarka

Globals:
  Function:
    Timeout: 5

Resources:
  MemeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: meme_function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Meme:
          Type: Api
          Properties:
            Path: /meme
            Method: get

Outputs:
  MemeApi:
    Description: "API Gateway endpoint URL for Prod stage for Meme function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/meme/"
  MemeFunction:
    Description: "Meme Lambda Function ARN"
    Value: !GetAtt MemeFunction.Arn
  MemeFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt MemeFunctionRole.Arn
